branches:
  only:
    - master
    - feat/offline-only-index
os: osx
language: objective-c
matrix:
  include:
    - osx_image: xcode9
      env: SWFT=4.0 PLAT=macOS
    - osx_image: xcode9
      env: SWFT=4.0 PLAT=iOS
    - osx_image: xcode9
      env: SWFT=4.0 PLAT=watchOS
    - osx_image: xcode9
      env: SWFT=3.2 PLAT=macOS
    - osx_image: xcode9
      env: SWFT=3.2 PLAT=iOS
    - osx_image: xcode9
      env: SWFT=3.2 PLAT=watchOS
    - osx_image: xcode8.3
      env: SWFT=3.1 PLAT=macOS
    - osx_image: xcode8.3
      env: SWFT=3.1 PLAT=iOS
    - osx_image: xcode8.3
      env: SWFT=3.1 PLAT=watchOS
install:
  - pod install --repo-update
before_script:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - travis_retry travis_wait 30 bash run_test.sh
